/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/3D LUPER.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0.536, 0.133, 1.935]}
        scale={[3.267, 1, 3.267]}
      />
      <group position={[-0.179, 0.703, 0.132]} rotation={[-Math.PI, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQMESA_ARD-geom"].geometry}
          material={materials.TQMESA_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQMESA_ARD-geom_1"].geometry}
          material={materials.TQMESA_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQMESA_ARD-geom_2"].geometry}
          material={materials.TQMESA_ARD_edge}
        />
      </group>
      <group position={[0.397, 0.808, 0.176]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQPATA_ARD-geom"].geometry}
          material={materials.TQPATA_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQPATA_ARD-geom_1"].geometry}
          material={materials.TQPATA_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQPATA_ARD-geom_2"].geometry}
          material={materials.TQPATA_ARD_edge}
        />
      </group>
      <group position={[-0.768, 0.806, 0.177]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQPATA222_ARD-geom"].geometry}
          material={materials.TQPATA222_ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQPATA222_ARD-geom_1"].geometry}
          material={materials.TQPATA222_ARD_back}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQPATA222_ARD-geom_2"].geometry}
          material={materials.TQPATA222_ARD_edge}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3D LUPER.gltf");